"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeftIcon, CheckIcon, CopyIcon, InfoIcon, TerminalIcon } from "lucide-react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ClearAdminTokenButton } from "@/components/clear-admin-token";
import { PageHeader } from "@/components/page-header";
import { adminTokenExpiresInMs, fmtRemaining, getAdminToken } from "@/lib/admin-token";
import { getPhase, type PhaseNumber } from "@/lib/onboarding-phases";

const TOKEN_PLACEHOLDER = "<paste from /killswitch or /onboarding/1-init>";

function buildCurl(endpoint: string, exampleBody: Record<string, unknown>, edgeUrl: string, token: string): string {
  const tokenLine = token ? token : TOKEN_PLACEHOLDER;
  const body = JSON.stringify(exampleBody, null, 2);
  return [
    `curl -sSf -X POST '${edgeUrl}${endpoint}' \\`,
    `  -H 'content-type: application/json' \\`,
    `  -H 'x-arbx-admin-token: ${tokenLine}' \\`,
    `  -H 'x-arbx-actor: <operator-handle>' \\`,
    `  --data '${body.replace(/'/g, "'\\''")}'`,
  ].join("\n");
}

export function OnboardingPhaseStub({ n, edgeUrl }: { n: PhaseNumber; edgeUrl: string }) {
  const phase = getPhase(n);
  const [token, setToken] = useState("");
  const [tokenExpiresIn, setTokenExpiresIn] = useState(0);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setToken(getAdminToken());
    setTokenExpiresIn(adminTokenExpiresInMs());
  }, []);

  const curl = useMemo(
    () => buildCurl(phase.endpoint, phase.exampleBody, edgeUrl, token),
    [phase.endpoint, phase.exampleBody, edgeUrl, token],
  );

  async function copy() {
    try {
      await navigator.clipboard.writeText(curl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API can fail under iframes/insecure contexts. Surface as
      // a user-visible nudge rather than a silent failure.
      window.prompt("Copy this curl manually:", curl);
    }
  }

  return (
    <>
      <PageHeader
        title={`Phase ${phase.n} — ${phase.title}`}
        lede={phase.blurb}
        actions={
          <Link
            href="/onboarding"
            className="inline-flex items-center gap-2 rounded-md border px-3 py-1.5 text-sm hover:bg-accent"
          >
            <ArrowLeftIcon className="size-4" /> Back
          </Link>
        }
      />

      <Alert variant="info" className="mb-6">
        <InfoIcon />
        <AlertTitle>UI form ships in Sprint 2</AlertTitle>
        <AlertDescription>
          Today, complete this phase by calling the admin endpoint below. The
          contract is documented in <code className="font-mono">docs/governance/DATA-MATRIX.md</code>.
          The body shape shown here is illustrative — it never invents values for you.
        </AlertDescription>
      </Alert>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="text-base">Solicits</CardTitle>
          <CardDescription>
            Values the operator provisions from their own secret manager. Nothing here is
            generated by the application.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="flex flex-wrap gap-2 text-xs">
            {phase.solicits.map((x) => (
              <li key={x}>
                <code className="rounded bg-muted px-2 py-0.5 font-mono">{x}</code>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <Card className="mb-6">
        <CardHeader>
          <div className="flex items-start justify-between gap-3">
            <div>
              <CardTitle className="text-base flex items-center gap-2">
                <TerminalIcon className="size-4" /> Complete via admin endpoint
              </CardTitle>
              <CardDescription>
                <code className="font-mono">POST {phase.endpoint}</code>
                {" "}— routes through the edge (worker / dev-local), then api-server enforces the admin token.
              </CardDescription>
            </div>
            <Badge variant={token ? "success" : "outline"} className="shrink-0">
              {token ? "token loaded" : "no token"}
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="flex flex-col gap-3">
          {token && tokenExpiresIn > 0 && (
            <p className="text-xs text-muted-foreground">
              Using token from this browser. Auto-clears in <strong>{fmtRemaining(tokenExpiresIn)}</strong>.
            </p>
          )}
          {!token && (
            <p className="text-xs text-muted-foreground">
              No admin token in this browser yet. Paste it on{" "}
              <Link className="underline" href="/onboarding/1-init">phase 1</Link> or{" "}
              <Link className="underline" href="/killswitch">/killswitch</Link>, then return.
            </p>
          )}
          <pre className="overflow-x-auto rounded-md border bg-card/40 p-3 font-mono text-xs leading-relaxed">
{curl}
          </pre>
          <div className="flex flex-wrap gap-2">
            <Button type="button" size="sm" onClick={copy}>
              {copied ? <CheckIcon /> : <CopyIcon />}
              {copied ? "copied" : "Copy curl"}
            </Button>
            <ClearAdminTokenButton
              onCleared={() => { setToken(""); setTokenExpiresIn(0); }}
            />
          </div>
        </CardContent>
      </Card>

      <p className="text-xs text-muted-foreground">
        When the proper UI ships, this page is replaced by a form like{" "}
        <Link className="underline" href="/onboarding/1-init">phase 1</Link>. Until then,
        the operator console is the source of truth for <em>what</em> needs solicitation —
        not <em>how</em>. Calling the endpoint directly is the supported path.
      </p>
    </>
  );
}
