#!/usr/bin/env python3
"""Generate shared-ts/src/contracts/strategy-kinds.ts from the cartridge registry.

Canonical `strategy_kind` values = the 5 base strategy families + every cartridge
filename stem in backend/searcher-rs/cartridges/strategies/*.rhai. The runtime
uses the filename stem as the cartridge identity (cartridge_loader file_stem()),
and the frontend's familyOf() derives the family from the `mev_<group>_` prefix,
so the stem is the correct canonical strategy_kind.

Adding a `.rhai` cartridge and re-running this generator adds its stem to the
`StrategyKind` zod enum automatically. Mirrors the gen_math_operator_mapping.py
pattern (single source of truth -> generated TS).

Usage: python scripts/gen_strategy_kinds.py
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CARTRIDGE_DIR = ROOT / "backend" / "searcher-rs" / "cartridges" / "strategies"
OUT_FILE = ROOT / "shared-ts" / "src" / "contracts" / "strategy-kinds.ts"

# The 5 base strategy families (legacy / topology grouping). Kept for backward
# compatibility with historical rows and any residual native-engine emissions.
BASE_KINDS = ["dex_arb", "triangular", "backrun", "liquidation", "flashloan_arb"]


def collect_cartridge_stems() -> list[str]:
    if not CARTRIDGE_DIR.is_dir():
        sys.exit(f"ERROR: cartridge dir not found: {CARTRIDGE_DIR}")
    return sorted(p.stem for p in CARTRIDGE_DIR.glob("*.rhai"))


def main() -> None:
    stems = collect_cartridge_stems()
    # Dedupe preserving order (base first, then sorted cartridge stems).
    seen: set[str] = set()
    kinds: list[str] = []
    for k in BASE_KINDS + stems:
        if k and k not in seen:
            seen.add(k)
            kinds.append(k)

    n_base = len(BASE_KINDS)
    n_cart = len(kinds) - n_base

    lines = [
        "// AUTO-GENERATED by scripts/gen_strategy_kinds.py — do not edit by hand.",
        "// Canonical `strategy_kind` values: the 5 base strategy families + every",
        "// cartridge filename stem in backend/searcher-rs/cartridges/strategies/*.rhai.",
        "// The runtime uses the filename stem as the cartridge identity; the frontend's",
        "// familyOf() derives the family from the `mev_<group>_` prefix.",
        "// Adding a .rhai cartridge and re-running the generator adds its stem here.",
        f"// Source: {len(kinds)} kinds ({n_base} base + {n_cart} cartridges).",
        "",
        'import { z } from "zod";',
        "",
        "export const STRATEGY_KINDS = [",
    ]
    for k in kinds:
        lines.append(f'  "{k}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export const StrategyKind = z.enum(STRATEGY_KINDS);")
    lines.append("export type StrategyKind = z.infer<typeof StrategyKind>;")
    lines.append("")

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_FILE.relative_to(ROOT)} ({len(kinds)} kinds: {n_base} base + {n_cart} cartridges)")


if __name__ == "__main__":
    main()
